---
title: Agorama
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: img
  values:
    image: true
- scope:
    path: images
  values:
    image: true
email: admin@agorama.org.uk
description: Agorama main home page.
twitter_username: agorama_
github_username: agoramaHub
instagram_username: agorama_
keep_files:
- ".dat"
- ".datignore"
- dat.json
- robots.txt
markdown: kramdown
excerpt_separator: "<!--more-->"
theme: minima
plugins:
- jekyll-feed
- jekyll-include-cache
iis_slider_array: []
exclude:
- Gemfile
- Gemfile.lock
